apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-queue-sa
  namespace: keda-ns
  annotations:
    azure.workload.identity/use: "true"
    azure.workload.identity/client-id: "f653022e-989d-474c-9957-016cf258d14f"
