---
# 1️⃣ ServiceAccount for KEDA ScaledObject pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-queue-sa
  namespace: keda
  annotations:
    azure.workload.identity/client-id: "6ab8e776-cb76-42c9-915e-e4d03e9d0bc5"

---
# 2️⃣ TriggerAuthentication using Workload Identity
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azqueue-auth-wi
  namespace: keda
spec:
  podIdentity:
    provider: azure-workload
    identityId: "6ab8e776-cb76-42c9-915e-e4d03e9d0bc5"
