apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azqueue-auth-wi
  namespace: keda
spec:
  podIdentity:
    provider: azure-workload
    identityId: "6ab8e776-cb76-42c9-915e-e4d03e9d0bc5"
